--ALTER TABLE TRS_ETA_INVOICES_LINES
 --DROP PRIMARY KEY CASCADE;

--DROP TABLE TRS_ETA_INVOICES_LINES CASCADE CONSTRAINTS;

CREATE TABLE TRS_ETA_INVOICES_LINES
(
  CUSTOMER_TRX_ID                 NUMBER(15)    NOT NULL,
  CUSTOMER_TRX_LINE_ID            NUMBER(15)    NOT NULL,
  INV_LINES_DESC                  VARCHAR2(4000 BYTE),
  INV_LINES_ITEM_TYPE             VARCHAR2(100 BYTE),
  INV_LINES_ITEM_CODE             VARCHAR2(240 BYTE),
  INV_LINES_UNIT_TYPE             VARCHAR2(100 BYTE),
  INV_LINES_QTY                   NUMBER,
  INV_LINES_UNIT_VAL_CURR_SOLD    VARCHAR2(100 BYTE),
  INV_LINES_UNIT_VAL_AMOUNT_EGP   NUMBER,
  INV_LINES_UNIT_VAL_AMOUNT_SOLD  NUMBER,
  INV_LINES_UNIT_VAL_CURR_RATE    NUMBER,
  INV_LINES_SALES_TOTAL           NUMBER,
  INV_LINES_TOTAL                 NUMBER,
  INV_LINES_VAL_DIFF              NUMBER,
  INV_LINES_TOTAL_TAX_FEES        NUMBER,
  INV_LINES_NET_TOTAL             NUMBER,
  INV_LINES_ITEM_DISC             NUMBER,
  INV_LINES_DISCOUNT_RATE         NUMBER,
  INV_LINES_DISCOUNT_AMT          NUMBER,
  INV_LINES_TAX_ITEM_TYPE_vat         VARCHAR2(100 BYTE),
  INV_LINES_TAX_ITEM_AMT_vat          NUMBER,
  INV_LINES_TAX_ITEM_SUBTYPE_vat      VARCHAR2(100 BYTE),
  INV_LINES_TAX_ITEM_RATE_vat         NUMBER,
  INV_LINES_TAX_ITEM_TYPE_wht         VARCHAR2(100 BYTE),
  INV_LINES_TAX_ITEM_AMT_wht         NUMBER,
  INV_LINES_TAX_ITEM_SUBTYPE_wht      VARCHAR2(100 BYTE),
  INV_LINES_TAX_ITEM_RATE_wht         NUMBER,
  INV_LINES_INTERNAL_CODE         VARCHAR2(4000 BYTE)
);


CREATE INDEX TRS_ETA_INV_CUST_TRX_LINE_ID ON TRS_ETA_INVOICES_LINES
(CUSTOMER_TRX_LINE_ID);


CREATE INDEX  TRS_ETA_INV_LINES_CUST_TRX_ID ON TRS_ETA_INVOICES_LINES
(CUSTOMER_TRX_ID);


ALTER TABLE TRS_ETA_INVOICES_LINES ADD (
  CONSTRAINT TRS_ETA_INVOICES_LINES_PK
  PRIMARY KEY
  (CUSTOMER_TRX_LINE_ID)
  USING INDEX TRS_ETA_INV_CUST_TRX_LINE_ID
  ENABLE VALIDATE);

ALTER TABLE TRS_ETA_INVOICES_LINES ADD (
  CONSTRAINT TRS_ETA_INVOICES_LINES_R01 
  FOREIGN KEY (CUSTOMER_TRX_ID) 
  REFERENCES TRS_ETA_INVOICES_HEADER (CUSTOMER_TRX_ID)
  ENABLE VALIDATE);
